### ISSUE TITLE
problems installing Wireguard client on HACS

### ISSUE THREAD

**Issue by Antonio610821** [bigmoby/addon-wireguard-client#10]
I have installed Hassos on Raspberry 4 and I have installed HACS and it works regularly.
I wanted to install wireguard client for the Snat problem so I tried to add the repository indicated on GitHub to the HACS configuration but I got this error:
"Repostitory structure for v0.1.7 is not compliant"
what am I wrong? What is the correct procedure for installing the custom component on Hassos?
Thanks Antonio

**Comment by bigmoby** [comment]
> I have installed Hassos on Raspberry 4 and I have installed HACS and it works regularly.
> I wanted to install wireguard client for the Snat problem so I tried to add the repository indicated on GitHub to the HACS configuration but I got this error:
> "Repostitory structure for v0.1.7 is not compliant"
> what am I wrong? What is the correct procedure for installing the custom component on Hassos?
> Thanks Antonio
> 

Hi @Antonio610821 
Wire guard Client isn't an HACS integration but an Hassio Add-on so it's installation is different. Please follow these steps:
- under Supervisor menu add new repository and put this url ```https://github.com/bigmoby/hassio-repository-addon```
- reload the addon list
- Wireguard Client appears in the addon list
- install the addon
- configure it (please follow its documentation) and start

I wanna suggest you an Italian guide under the Vincenzo Caputo blog, please take a look! 😉

Cheers, 
Fabio

P.s.: if this addon could be a good solution for you, please consider to contribute to this project 🙏
