### ISSUE TITLE
After adding the reposity and refreshing the add-on store I cannot find the wireguard client

### ISSUE THREAD

**Issue by damarges** [bigmoby/addon-wireguard-client#19]
After adding the reposity and refreshing the add-on store I cannot find the wireguard client

**Comment by bigmoby** [comment]
Hi @damarges please you have to add this URL `https://github.com/bigmoby/hassio-repository-addon` into custom repository URL's section.

**Comment by damarges** [comment]
thats what I did. no addon showing up I could install :/

**Comment by damarges** [comment]
well now after done it for the ike 5th or 6th time and refreshing and so on. now it shows up :)

**Comment by bigmoby** [comment]
Probably a browser cache issue.
