### ISSUE TITLE
Violating upstream copyright license

### ISSUE THREAD

**Issue by frenck** [bigmoby/addon-wireguard-client#2]
# Problem/Motivation

Hi there,

I'm fine with having forks, however, you have to adhere to the MIT license and restore my name and authorship.

Please read the upstream license: <https://github.com/hassio-addons/addon-wireguard/blob/master/LICENSE.md>

![image](https://user-images.githubusercontent.com/195327/101980336-def61f00-3c64-11eb-9d74-eae959d1c9c9.png)

**Comment by bigmoby** [comment]
Hi @frenck sure my fault I correct it immediately. Many thanks, Fabio
