### ISSUE TITLE
set MTU size

### ISSUE THREAD

**Issue by photogeen** [bigmoby/addon-wireguard-client#23]
Hi,

please add the ability to set the MTU size.
I have one client that can connect but the default mtu 1420 is too high for it's network (CGNAT).

I tried to include MTU: 1412 but in the log i can see that wg is starting with 1420.

**Comment by bigmoby** [comment]
Hi @photogeen , please try with this release: https://github.com/bigmoby/addon-wireguard-client/releases/tag/v0.2.1
I hope it could be useful for you
