### ISSUE TITLE
JSON format

### ISSUE THREAD

**Issue by SrvRpi** [bigmoby/addon-wireguard-client#27]
How to correctly describe HA sensors? Does REST return the correct JSON format?

sensor:
  - platform: rest
    resource: http://xxxxxxxx-wireguard-client

`{"peer_1":"{"endpoint":xx.xx.xx.xx:51820,"latest_handshake":Thu Jun 8 11:14:28 EEST 2023,"transfer_rx":219000,"transfer_tx":86940}"}`

Maybe it should return:

`{"peer_1":{"endpoint":xx.xx.xx.xx:51820,"latest_handshake":Thu Jun 8 11:14:28 EEST 2023,"transfer_rx":219000,"transfer_tx":86940}}`

And even better:

`{"peer_1":{"endpoint":"xx.xx.xx.xx:51820","latest_handshake":"Thu Jun 8 11:14:28 EEST 2023","transfer_rx":"219000","transfer_tx":"86940"}}`

**Comment by bigmoby** [comment]
Hi @SrvRpi 
thanks for this issue notification 
Anyway please feel free to create a PR with the suggested fix 👍
I could try to have the time to fix it but at moment I don't know when.

**Comment by bigmoby** [comment]
Thank you @olpal 🙌
