### ISSUE TITLE
fdm5591

### ISSUE THREAD

**Issue by sgeeurickx** [bigmoby/addon-wireguard-client#3]
Wireguard is correctly connected to the other peer, but my HA is unable to access any device. 

Any idea ?

**Comment by bigmoby** [comment]
Hi @sgeeurickx please if you could give me more informations as current wireguard addon configuration (please obfuscate sensitive data for your security).

**Comment by sgeeurickx** [comment]
I'm running HA on a Raspberry Pi on RassOS.  Running wireguard-addon to act as a server (I can connect from the wireguard client on my phone).  I'm running another Raspberry Pi with the same config on a remote network.  As I can see in the logs, wireguard-client-addon from location A is correctly connected to wireguard-addon on location B.  Anyway, if I try to ping any device in location B from HA terminal on location A, I have no answer.

Location A "client" config :
`interface:
  private_key: ********
  address: 172.27.66.5
  dns:
    - 192.168.0.38
peer:
  public_key: ********
  pre_shared_key: ********
  endpoint: '********.duckdns.org:51820'
  allowed_ips:
    - 192.168.0.0/24
  persistent_keep_alive: '25'`

Location B (server) :
`server:
  host: ******.duckdns.org
  addresses:
    - 172.27.66.1
  dns:
    - 172.30.32.1
  - name: ptxgrx
    addresses:
      - 172.27.66.5
    allowed_ips: []
    client_allowed_ips:
      - 192.168.0.0/24
      - 172.30.32.0/24
`
My ultimate goal is to create a site-to-site VPN, so I guess I will then have to add static routes on my router.

**Comment by bigmoby** [comment]
> Running wireguard-addon to act as a server

I'm sorry, you're using the wrong add-on! This is a Wireguard Client add-on.
