### ISSUE TITLE
Home-Assistant working as a NAT Server for VPN client connection

### ISSUE THREAD

**Issue by JRFabbi** [bigmoby/addon-wireguard-client#31]
Is there a way to do it? Because I can ping from home-assistant all networks connected thru VPN client but I can't use them from others computers on the same network using home-assistant as a gateway for them even if I put rules for this on iptables.

Is this configuration possible?

**Comment by bigmoby** [comment]
Hi @JRFabbi , thanks for using this add-on. 
Unfortunately your question is not related to an issue affected by the Wireguard add-on. I cannot help your, sorry
