### ISSUE TITLE
Unable to resolve dns

### ISSUE THREAD

**Issue by EgertKanep** [bigmoby/addon-wireguard-client#39]
# Problem/Motivation

Unable to use dns aadress for host.DuckDNS worked, but not tplinkdns. I have confirmed this dns works on android wg client.

## Steps to reproduce

Try using different dns providers.

## Proposed changes

If someone can point me in the right direction and has idea, what could be causing it, I'd be glad to investigate it further.

**Comment by bigmoby** [comment]
I'm sorry but I'm not able to help you...it's not an issue related to this add-on. Please try to use a different dns provider.
