### ISSUE TITLE
安装不上？

### ISSUE THREAD

**Issue by laotan1977** [bigmoby/addon-wireguard-client#44]
# Problem/Motivation

> (Why the issue was filed)

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes
![微信截图_20241226150945](https://github.com/user-attachments/assets/0c12b590-363a-4499-b266-1155d5974a8b)

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by bigmoby** [comment]
Hi @laotan1977 
Please check your internet connection. It's not related to this addon, I'm sorry.
