### ISSUE TITLE
Connection not possible 

### ISSUE THREAD

**Issue by michl270** [bigmoby/addon-wireguard-client#8]
I am running two home assistant instaces in two separate houses. 

At my major home, I am running the home assistant Wireguard-server addon with following config:
server:
  host: [IP]:[PORT]
  addresses:
    - 172.27.66.1
  dns: []
peers:
  - name: any name
    addresses:
      - 172.27.66.202
    allowed_ips: []
    client_allowed_ips: []
  - name: any second name
    addresses:
      - 172.27.66.203
    allowed_ips: []
    client_allowed_ips: []

In my second home, I have a RPI3 runs home assistant with the Wireguard-client. Config:
interface:
  private_key: [PRIVATE KEY]
  address: 172.27.66.203/24
  dns:
    - 172.30.32.3
  post_up: iptables -t nat -A POSTROUTING -o wg0 -j MASQUERADE
  post_down: iptables -t nat -D POSTROUTING -o wg0 -j MASQUERADE
peer:
  public_key: [PIUBLIC KEY]
  endpoint: [IP]:[PORT]
  allowed_ips:
    - 10.9.0.0/24
  persistent_keep_alive: 25

**Unfortunately, the connection between the two networks cannot be established. I use the wireguard-server for several connections with wireguard-clients (e.g. wireguard app for windows, iOS) and everything is working ok there - only the wireguard-client-addon does not want to connect to the VPN-server.
Could you please advice, how to get the connection running :-)**

Thanks in advance for your assistance!

PS:

LOG CLIENT:
[19:12:20] INFO: Requesting current status from WireGuard Client...
interface: wg0
  public key: A/HzBwQEFnHbR8vXx/F75oFBEkYF7k8AiCBe8P8qd0g=
  private key: (hidden)
  listening port: 47677
peer: LTji/hiLAjUsRSvpjEdgX54SDn8uaWTjujxGEQEq8Uo=
  preshared key: (hidden)
  endpoint: 185.248.151.188:51850
  allowed ips: 10.9.0.0/24
  transfer: 0 B received, 888 B sent
  persistent keepalive: every 25 seconds

Both devices are up to date!

**Comment by michl270** [comment]
Additional info:
When I use this config on my phone or windows pc, everything is working fine:
[Interface]
PrivateKey = PRIVATEKEY
Address = 172.27.66.203/24
DNS = 172.30.32.3

[Peer]
PublicKey = PUBLICKEY
Endpoint = IP:51850
AllowedIPs = 0.0.0.0/0
PersistentKeepalive = 25

--> There is no problem with my server config but with the client config entry.

Pls help and I will buy you a coffee :-)

**Comment by bigmoby** [comment]
> --> There is no problem with my server config but with the client config entry.
> 
> Pls help and I will buy you a coffee :-)

Dear @michl270 ,
the issues could be tons in your environment from some firewall misconfiguration to the simplest typo in your config. I could suggest you to try to recheck your network config and exposed ports.
The GitHub issue section is for problem regarding the project itself if any bug happen and not for private assistance. Apart from that, the "buy me a coffee" is not for clarity but for support this project! Trust me, with a coffee I don't became rich.
